name: Automatic Releases

on: push

jobs:
  build:

    runs-on: "ubuntu-latest"
    permissions:
      contents: write
      packages: write
      pull-requests: "read"

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'
          server-id: github

      - name: Build with Maven
        run: mvn package assembly:single

      - name: "Create Release Files"
        run: |
          java -jar .github/packr/packr-all-4.0.0.jar .github/packr/linux.json
          java -jar .github/packr/packr-all-4.0.0.jar .github/packr/win.json
          cd .github/packr/build/linux64
          zip -m -r linux64 *
          cd ../windows64
          zip -m -r windows64 *

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            .github/packr/build/linux64/linux64.zip
            .github/packr/build/windows64/windows64.zip

      - uses: actions/delete-package-versions@v4
        with:
          package-version-ids: "25988635"
          package-name: "com.monique.sectgeon"
          package-type: "maven"

      - name: Publish to GitHub Packages Apache Maven
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "<settings><servers><server><id>github</id><username>moniq-e</username><password>${GITHUB_TOKEN}</password></server></servers></settings>" > ~/.m2/settings.xml
          mvn deploy
