name: Automatic Releases

on: push

jobs:
  release:

    runs-on: "ubuntu-latest"
    permissions:
      contents: write
      packages: write
      pull-requests: "read"

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'
          server-id: github

      - name: Build with Maven
        run: mvn package assembly:single

      - name: Delete Package
        run: |
          curl --request DELETE \
          --url https://api.github.com/user/packages/maven/com.monique.sectgeon \
          --header 'Accept: application/vnd.github+json' \
          --header 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'X-GitHub-Api-Version: 2022-11-28'

      - name: Publish to GitHub Packages Apache Maven
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "<settings><servers><server><id>github</id><username>moniq-e</username><password>${GITHUB_TOKEN}</password></server></servers></settings>" > ~/.m2/settings.xml
          mvn deploy

      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: oracle-actions/setup-java@v1
        with:
          uri: https://download.oracle.com/java/19/latest/jdk-19_windows-x64_bin.zip

      - name: Test
        run: ls

      - name: Build with Maven
        run: mvn package assembly:single

      - name: Create release files
        run: |
          java -jar .github/packr/packr-all-4.0.0.jar .github/packr/linux.json
          java -jar .github/packr/packr-all-4.0.0.jar .github/packr/win.json
          cd .github/packr/build/linux64
          zip -m -r linux64 *
          cd ../windows64
          zip -m -r windows64 *

      - name: Publish release files
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: false
          title: Development Build
          files: |
            .github/packr/build/linux64/linux64.zip
            .github/packr/build/windows64/windows64.zip
